export const AUTH_LOGAR_REQUEST = 'AUTH_LOGAR_REQUEST'
export const AUTH_LOGAR_SUCCESS = 'AUTH_LOGAR_SUCCESS'
export const AUTH_LOGAR_FAILURE = 'AUTH_LOGAR_FAILURE'
export const AUTH_ERRO_RESET = 'AUTH_ERRO_RESET'
export const AUTH_DESLOGAR = 'AUTH_DESLOGAR'
export const AUTH_REFRESHTOKEN = 'AUTH_REFRESHTOKEN'

export const ROTEIRO_CARREGAR_REQUEST = 'ROTEIRO_CARREGAR_REQUEST'
export const ROTEIRO_CARREGAR_SUCCESS = 'ROTEIRO_CARREGAR_SUCCESS'
export const ROTEIRO_CARREGAR_FAILURE = 'ROTEIRO_CARREGAR_FAILURE'


export const PARCEIRO_CARREGAR_REQUEST = 'PARCEIRO_CARREGAR_REQUEST'
export const PARCEIRO_CARREGAR_SUCCESS = 'PARCEIRO_CARREGAR_SUCCESS'
export const PARCEIRO_CARREGAR_FAILURE = 'PARCEIRO_CARREGAR_FAILURE'
