export const AUTH_LOGAR_REQUEST = 'AUTH_LOGAR_REQUEST'
export const AUTH_LOGAR_SUCCESS = 'AUTH_LOGAR_SUCCESS'
export const AUTH_LOGAR_FAILURE = 'AUTH_LOGAR_FAILURE'

export const AUTH_ERRO_RESET = 'AUTH_ERRO_RESET'
export const AUTH_DESLOGAR = 'AUTH_DESLOGAR'
export const AUTH_REFRESHTOKEN = 'AUTH_REFRESHTOKEN'


export const RESETSENHA_PEDIDO_REQUEST = 'RESETSENHA_PEDIDO_REQUEST'
export const RESETSENHA_PEDIDO_SUCCESS = 'RESETSENHA_PEDIDO_SUCCESS'
export const RESETSENHA_PEDIDO_FAILURE = 'RESETSENHA_PEDIDO_FAILURE'

export const RESETSENHA_CODIGO_REQUEST = 'RESETSENHA_CODIGO_REQUEST'
export const RESETSENHA_CODIGO_SUCCESS = 'RESETSENHA_CODIGO_SUCCESS'
export const RESETSENHA_CODIGO_FAILURE = 'RESETSENHA_CODIGO_FAILURE'

export const RESETSENHA_NOVASENHA_REQUEST = 'RESETSENHA_NOVASENHA_REQUEST'
export const RESETSENHA_NOVASENHA_SUCCESS = 'RESETSENHA_NOVASENHA_SUCCESS'
export const RESETSENHA_NOVASENHA_FAILURE = 'RESETSENHA_NOVASENHA_FAILURE'

export const RESETSENHA_SAIR = 'RESETSENHA_SAIR'

export const ROTEIRO_CARREGAR_REQUEST = 'ROTEIRO_CARREGAR_REQUEST'
export const ROTEIRO_CARREGAR_SUCCESS = 'ROTEIRO_CARREGAR_SUCCESS'
export const ROTEIRO_CARREGAR_FAILURE = 'ROTEIRO_CARREGAR_FAILURE'


export const PARCEIRO_CARREGAR_REQUEST = 'PARCEIRO_CARREGAR_REQUEST'
export const PARCEIRO_CARREGAR_SUCCESS = 'PARCEIRO_CARREGAR_SUCCESS'
export const PARCEIRO_CARREGAR_FAILURE = 'PARCEIRO_CARREGAR_FAILURE'
